In [2]:
!pip install scikit-hts

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-hts
  Downloading scikit_hts-0.5.12-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: scipy>=1.3.2 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-hts) (1.7.3)
Requirement already satisfied: scikit-learn>=0.21.3 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-hts) (1.0.2)
Requirement already satisfied: statsmodels>=0.12.0 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-hts) (0.13.2)
Requirement already satisfied: tqdm>=4.43 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-hts) (4.63.0)
Requirement already satisfied: pandas>=0.25.3 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-hts) (1.3.5)
Requirement already satisfied: numpy>=1.17.4 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-hts) (1.21.5)
Requirement already satisfied: pytz>=2017.3 in /scratch/ssd001/pkgs/jupyterhub/lib/python3.7/site-packages (from pandas>=0.25.3->scikit-hts) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /scratch/ssd001/pkgs/jupyterhub/lib/python3.7/site-packages (from pandas>=0.25.3->scikit-hts) (2.8.1)
Requirement already satisfied: six>=1.5 in /scratch/ssd001/pkgs/jupyterhub/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->scikit-hts) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-learn>=0.21.3->scikit-hts) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from scikit-learn>=0.21.3->scikit-hts) (3.1.0)
Requirement already satisfied: patsy>=0.5.2 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from statsmodels>=0.12.0->scikit-hts) (0.5.2)
Requirement already satisfied: packaging>=21.3 in /ssd003/home/chengchen/.local/lib/python3.7/site-packages (from statsmodels>=0.12.0->scikit-hts) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /scratch/ssd001/pkgs/jupyterhub/lib/python3.7/site-packages (from packaging>=21.3->statsmodels>=0.12.0->scikit-hts) (2.4.7)
Installing collected packages: scikit-hts
Successfully installed scikit-hts-0.5.12

### try scikit_hts with a naive hts (1 observation for n hierarchies)

In [2]:
import numpy as np
import pandas as pd 
import hts  # To install: pip install scikit-hts
import collections
from scipy.optimize import lsq_linear

In [3]:
# a naive hts
hts_df = pd.DataFrame([{'total': 2, 
                        'CA': 1.4, 'TX': 1.8, 'WI': 1.9, 
                        'CA_1': 0.8, 'CA_2': 0.6, 'CA_3': 0.9, 'CA_4': 0.3,
                        'TX_1': 0.03, 'TX_2': 0.5, 'TX_3': 0.5, 
                        'WI_1': 1.6, 'WI_2': 1.2, 'WI_3': 1.5
                        }])

In [4]:
hts_df

,total,CA,TX,WI,CA_1,CA_2,CA_3,CA_4,TX_1,TX_2,TX_3,WI_1,WI_2,WI_3
0,2,1.4,1.8,1.9,0.8,0.6,0.9,0.3,0.03,0.5,0.5,1.6,1.2,1.5

In [5]:
states = ['CA', 'TX', 'WI']
stores = ['CA_1', 'CA_2', 'CA_3', 'CA_4', 'TX_1', 'TX_2', 'TX_3', 'WI_1', 'WI_2', 'WI_3']

# build the hierarchy tree as a dictionary

total = {'total': list(states)}
state_h = {k: [v for v in stores if v.startswith(k)] for k in states}
hierarchy = {**total, **state_h}

In [6]:
hierarchy

{'total': ['CA', 'TX', 'WI'],
 'CA': ['CA_1', 'CA_2', 'CA_3', 'CA_4'],
 'TX': ['TX_1', 'TX_2', 'TX_3'],
 'WI': ['WI_1', 'WI_2', 'WI_3']}

In [7]:
tree = hts.hierarchy.HierarchyTree.from_nodes(nodes=hierarchy, df=hts_df)
sum_mat, sum_mat_labels = hts.functions.to_sum_mat(tree)

In [8]:
tree

- total
   |- CA
   |  |- CA_1
   |  |- CA_2
   |  |- CA_3
   |  - CA_4
   |- TX
   |  |- TX_1
   |  |- TX_2
   |  - TX_3
   - WI
      |- WI_1
      |- WI_2
      - WI_3

In [9]:
pred_dict = collections.OrderedDict()
for label in sum_mat_labels:
    pred_dict[label] = pd.DataFrame(data=hts_df[label].values, columns=['yhat'])

In [10]:
# perform forecast reconciliation
revised = hts.functions.optimal_combination(pred_dict, sum_mat, method='OLS', mse={})
revised_forecasts = pd.DataFrame(data=revised,
                                 index=hts_df.index,
                                 columns=sum_mat_labels)
print(revised_forecasts)

      total        WI        TX        CA      CA_1      CA_2      CA_3  \
0  3.135606  1.648295  0.755795  0.731515  0.332879  0.132879  0.432879

       CA_4      TX_1      TX_2      TX_3      WI_1      WI_2      WI_3
0 -0.167121 -0.061402  0.408598  0.408598  0.716098  0.316098  0.616098

In [11]:
#  For non-negative reconciled forecasts
hat_mat = hts.functions.y_hat_matrix(pred_dict)
revised_nnls = np.dot(sum_mat, lsq_linear(sum_mat, hat_mat.flatten(), bounds=(0, np.inf))['x'])
revised_forecasts_nnls = pd.DataFrame(data=revised_nnls.reshape(1,-1),
                                 index=hts_df.index,
                                 columns=sum_mat_labels)

In [12]:
print(revised_forecasts_nnls)

      total        WI        TX        CA      CA_1      CA_2      CA_3  \
0  3.155263  1.633553  0.763158  0.758553  0.286184  0.086184  0.386184

           CA_4          TX_1      TX_2      TX_3      WI_1      WI_2  \
0  9.425493e-22  5.896338e-17  0.381579  0.381579  0.711184  0.311184

       WI_3
0  0.611184

### try hts with 28 observations at different hierarchies

In [13]:
# load m5 dataset
m5_input_path = "/ssd003/projects/forecasting_bootcamp/bootcamp_datasets/m5-forecasting-accuracy"
sell_price = pd.read_csv(f'{m5_input_path}/sell_prices.csv')
calendar = pd.read_csv(f'{m5_input_path}/calendar.csv')
train = pd.read_csv(f'{m5_input_path}/sales_train_evaluation.csv').set_index('id')
sample_sub = pd.read_csv(f'{m5_input_path}/sample_submission.csv')

In [14]:
cat_cols = ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']
ts_cols = [col for col in train.columns if col not in cat_cols]
ts_dict = {t: int(t[2:]) for t in ts_cols}

all_sales = pd.DataFrame(train[ts_cols].sum()).transpose()
all_sales['id_str'] = 'all'
all_sales = all_sales[ ['id_str'] +  [c for c in all_sales if c not in ['id_str']] ]

state_sales = train.groupby('state_id',as_index=False)[ts_cols].sum()
state_sales['id_str'] = state_sales['state_id'] 
state_sales = state_sales[ ['id_str'] +  [c for c in state_sales if c not in ['id_str']] ]
state_sales = state_sales.drop(['state_id'],axis=1)

store_sales = train.groupby('store_id',as_index=False)[ts_cols].sum()
store_sales['id_str'] = store_sales['store_id'] 
store_sales = store_sales[ ['id_str'] +  [c for c in store_sales if c not in ['id_str']] ]
store_sales = store_sales.drop(['store_id'],axis=1)

In [15]:
aggregates = pd.concat([all_sales,state_sales,store_sales],ignore_index=True)

In [16]:
true_last_28 = aggregates.set_index('id_str').transpose().rename(columns={'all':'total'}).iloc[-28:]

In [17]:
true_last_28.head()

id_str,total,CA,TX,WI,CA_1,CA_2,CA_3,CA_4,TX_1,TX_2,TX_3,WI_1,WI_2,WI_3
d_1914,38793,17524,10662,10607,4472,3926,6359,2767,3076,3883,3703,3166,4178,3263
d_1915,35487,15012,9933,10542,3703,3525,5289,2495,2853,3502,3578,3194,4148,3200
d_1916,34445,14836,9575,10034,3715,3527,5065,2529,2984,3256,3335,3267,3805,2962
d_1917,34732,14664,9655,10413,3618,3754,5015,2277,2664,3441,3550,3201,4342,2870
d_1918,42896,17180,12162,13554,4573,4382,5705,2520,3687,4023,4452,4143,5719,3692

In [18]:
# add noise to true sales numbers to get synthetic prediction data
mu, sigma = 1000, 2000
noise = np.random.normal(mu, sigma, [true_last_28.shape[0], true_last_28.shape[1]]) 
synthetic_pred_28 = true_last_28 + noise

In [19]:
synthetic_pred_28.head()

id_str,total,CA,TX,WI,CA_1,CA_2,CA_3,CA_4,TX_1,TX_2,TX_3,WI_1,WI_2,WI_3
d_1914,40794.107116,20310.249689,9283.261608,11004.055540,5487.305805,5498.787862,3046.911172,5198.534020,3620.383902,6877.755948,45.797552,3516.799089,5779.673448,3984.358339
d_1915,34954.648950,16808.107388,12793.262251,16312.313205,8743.859649,3365.877645,3628.556072,-386.036195,4728.552996,5017.702522,4561.018637,4068.695907,7234.410460,8756.880836
d_1916,31132.874621,14140.749744,5109.081951,11520.903229,3955.897598,4568.081110,4831.232509,-617.420420,5956.799642,5879.099755,7212.128420,1366.439263,2462.405932,5427.143101
d_1917,30368.712971,12122.124895,13258.973825,14447.428672,3684.577498,7045.110391,6479.014577,2035.247833,3591.433434,3712.474341,5918.338548,5166.654426,4724.959570,5255.415623
d_1918,40114.806980,14185.994233,14510.862423,15011.000810,4615.695121,3759.690174,6805.132582,1901.906411,7628.832797,7444.392874,4463.836759,9149.140924,6377.094184,7713.072764

In [20]:
tree = hts.hierarchy.HierarchyTree.from_nodes(nodes=hierarchy, df=synthetic_pred_28)
sum_mat, sum_mat_labels = hts.functions.to_sum_mat(tree)

In [21]:
pred_dict = collections.OrderedDict()
for label in sum_mat_labels:
    pred_dict[label] = pd.DataFrame(data=synthetic_pred_28[label].values, columns=['yhat'])

In [22]:
revised = hts.functions.optimal_combination(pred_dict, sum_mat, method='OLS', mse={})
revised_forecasts = pd.DataFrame(data=revised,
                                 index=synthetic_pred_28.index,
                                 columns=sum_mat_labels)

In [23]:
revised_forecasts
# we could see there are negative forecast values, e.g. CA_4 at day_1915, 1916, 1917

,total,WI,TX,CA,CA_1,CA_2,CA_3,CA_4,TX_1,TX_2,TX_3,WI_1,WI_2,WI_3
d_1914,40937.161764,11465.958389,9491.139571,19980.063805,5674.437041,5685.919098,3234.042409,5385.665256,3269.451292,6526.823338,-305.135058,2911.841593,5174.715952,3379.400843
d_1915,38585.947533,14525.757767,10448.291289,13611.898477,8308.769975,2930.787972,3193.466399,-821.125869,3442.225374,3731.374900,3274.691015,2223.952761,5389.667315,6912.137691
d_1916,31822.503786,10437.452621,8076.596543,13308.454622,4098.563554,4710.747066,4973.898465,-474.754464,2299.655884,2221.955997,3554.984662,1760.260705,2856.227374,5820.964543
d_1917,33717.166869,12110.988485,10738.451526,10867.726857,1590.521638,4951.054531,4384.958717,-58.808027,2763.501835,2884.542742,5090.406949,4154.640714,3712.945859,4243.401912
d_1918,42383.280697,15366.722288,14066.057138,12950.501271,3582.714367,2726.709420,5772.151828,868.925657,5805.164366,5620.724443,2640.168328,6524.945729,3752.898990,5088.877569
d_1919,51601.373469,13373.280000,11936.010010,26292.083459,4541.715661,7141.155700,9510.166113,5099.045985,3292.926736,3148.823202,5494.260072,4034.954384,3400.342105,5937.983511
d_1920,54544.717948,18086.853508,11610.560099,24847.304341,5621.654733,5442.106717,10428.873871,3354.669020,4733.900979,3406.296469,3470.362651,4376.204460,7941.360317,5769.288731
d_1921,46068.220944,14292.601174,15037.178545,16738.441226,6127.582697,2623.874920,4764.057547,3222.926062,971.339157,5639.495588,8426.343799,3682.824451,5064.559393,5545.217329
d_1922,49848.880603,16837.249175,12478.377644,20533.253784,1526.485015,6300.784533,8493.805431,4212.178806,1466.441737,4060.945311,6950.990597,2852.926930,7819.594871,6164.727374
d_1923,39686.479542,12974.584513,9404.295213,17307.599816,5875.921633,701.847159,8304.898593,2424.932431,366.167421,4873.477092,4164.650700,3636.986096,4720.779912,4616.818505
d_1924,42936.139744,14236.997691,10766.889962,17932.252091,2951.507622,6607.761126,5285.657799,3087.325545,4469.122185,4547.367476,1750.400301,2494.910835,4853.578716,6888.508140
d_1925,45332.207511,16913.482096,9622.877800,18795.847615,3429.159376,5028.645719,6125.243944,4212.798576,-34.037580,3414.777076,6242.138304,1917.743242,7775.054626,7220.684228
d_1926,56903.393692,19774.493581,15101.027408,22027.872703,8212.638482,2000.652135,6762.922560,5051.659525,740.447365,7214.182012,7146.398031,4872.237496,9382.106901,5520.149185
d_1927,48297.399154,15639.861230,12028.204331,20629.333593,5623.259408,5873.457837,7828.857702,1303.758647,1193.801435,7772.198150,3062.204745,5131.290307,5250.551347,5258.019577
d_1928,51346.731507,19625.710712,12226.113401,19494.907394,5725.590514,5640.414775,7915.431796,213.470309,3705.729695,5250.238081,3270.145625,4645.600592,9864.544152,5115.565968
d_1929,41599.020732,13401.834997,12257.575015,15939.610720,3425.291271,3824.013044,5204.235532,3486.070873,3345.578716,3048.765150,5863.231149,4058.058950,7326.877037,2016.899010
d_1930,44824.419646,14516.725496,14077.632677,16230.061473,4064.373168,658.383209,6012.617527,5494.687568,5592.621157,3581.410430,4903.601091,6657.160205,3569.635099,4289.930191
d_1931,44025.013390,12167.045963,14564.253047,17293.714380,1549.211659,2593.445146,9439.665240,3711.392334,6017.888085,3544.067808,5002.297154,3157.043909,6808.870478,2201.131576
d_1932,45545.389182,15523.566405,11761.173227,18260.649550,6413.798516,4117.129198,6012.809345,1716.912491,680.510386,5423.037379,5657.625461,5951.477867,7668.659304,1903.429234
d_1933,56340.727142,20056.530525,12795.997122,23488.199496,5983.551984,5968.803066,9087.810058,2448.034388,4116.613608,3476.394841,5202.988672,8561.598976,5537.978896,5956.952653
d_1934,60969.929855,18882.258609,18055.805263,24031.865983,6499.073609,4295.763963,8075.616031,5161.412379,6462.213010,5921.697770,5671.894483,6962.147425,8608.903476,3311.207708
d_1935,40822.391379,13072.549285,9733.103528,18016.738567,4056.670680,6538.248775,6328.059169,1093.759942,3568.704915,3593.591454,2570.807159,-681.956188,6476.611459,7277.894013
d_1936,41999.895914,12675.820051,12685.371590,16638.704272,3907.384073,3338.086604,7412.202239,1981.031357,3507.618355,3742.381406,5435.371828,6038.491547,4278.251613,2359.076891
d_1937,38710.932481,10117.094918,11289.519812,17304.317751,4526.205972,2107.872098,6925.504194,3744.735487,4737.457127,1737.334983,4814.727702,2510.717101,3130.633509,4475.744308
d_1938,38175.507667,11193.683282,8476.511223,18505.313162,7101.711191,2141.664514,5688.143073,3573.794384,3941.138606,623.448289,3911.924328,4146.201712,3994.123809,3053.357760
d_1939,45081.682111,14913.983363,12760.619345,17407.079403,5782.619575,4737.847257,5937.637311,948.975261,5894.593399,5591.972937,1274.053008,4789.148649,5009.355069,5115.479644
d_1940,52787.887107,17216.707239,13675.400915,21895.778953,4766.303806,9022.001763,6724.490166,1382.983219,2904.470230,4527.430654,6243.500032,4753.127636,4397.430020,8066.149582
d_1941,56199.581086,15441.782258,15036.680492,25721.118336,6481.822470,6786.323193,10528.102152,1924.870522,3232.002687,4816.629619,6988.048187,5011.957383,4761.029726,5668.795149

In [24]:
# add non-negative constraint when reconciliate
hat_mat = hts.functions.y_hat_matrix(pred_dict)

In [25]:
b_mat = []
for i in range(28):
    b_mat.append(lsq_linear(sum_mat, hat_mat[i].flatten(), bounds=(0, np.inf))['x'])

In [26]:
b_mat_final = np.stack(b_mat).transpose()
revised_nnls = np.dot(sum_mat, b_mat_final).transpose()
revised_forecasts_nnls = pd.DataFrame(data=revised_nnls,
                                 index=synthetic_pred_28.index,
                                 columns=sum_mat_labels)

In [27]:
revised_forecasts_nnls
# the previously negative forecasts are now close to 0 (CA_$ at d_1915, d_1916, d_1917)

,total,WI,TX,CA,CA_1,CA_2,CA_3,CA_4,TX_1,TX_2,TX_3,WI_1,WI_2,WI_3
d_1914,40968.781977,11442.243229,9571.771115,19954.767634,5668.112999,5679.595056,3227.718366,5.379341e+03,3.157200e+03,6414.571581,4.601192e-24,2.903937e+03,5166.810899,3371.495790
d_1915,38649.111062,14478.385121,10400.918643,13769.807298,8087.697626,2709.715623,2972.394049,2.155322e-22,3.426434e+03,3715.584018,3.258900e+03,2.208162e+03,5373.876433,6896.346808
d_1916,31859.023360,10410.062941,8049.206862,13399.753557,3970.745045,4582.928557,4846.079956,4.032505e-23,2.290526e+03,2212.826103,3.545855e+03,1.751131e+03,2847.097480,5811.834650
d_1917,33721.690563,12107.595714,10735.058755,10879.036093,1574.688707,4935.221600,4369.125786,8.430783e-12,2.762371e+03,2883.411818,5.089276e+03,4.153510e+03,3711.814935,4242.270988
d_1918,42383.280697,15366.722288,14066.057138,12950.501271,3582.714367,2726.709420,5772.151828,8.689257e+02,5.805164e+03,5620.724443,2.640168e+03,6.524946e+03,3752.898990,5088.877569
d_1919,51601.373469,13373.280000,11936.010010,26292.083459,4541.715661,7141.155700,9510.166113,5.099046e+03,3.292927e+03,3148.823202,5.494260e+03,4.034954e+03,3400.342105,5937.983511
d_1920,54544.717948,18086.853508,11610.560099,24847.304341,5621.654733,5442.106717,10428.873871,3.354669e+03,4.733901e+03,3406.296469,3.470363e+03,4.376204e+03,7941.360317,5769.288731
d_1921,46068.220944,14292.601174,15037.178545,16738.441226,6127.582697,2623.874920,4764.057547,3.222926e+03,9.713392e+02,5639.495588,8.426344e+03,3.682824e+03,5064.559393,5545.217329
d_1922,49848.880603,16837.249175,12478.377644,20533.253784,1526.485015,6300.784533,8493.805431,4.212179e+03,1.466442e+03,4060.945311,6.950991e+03,2.852927e+03,7819.594871,6164.727374
d_1923,39686.479542,12974.584513,9404.295213,17307.599816,5875.921633,701.847159,8304.898593,2.424932e+03,3.661674e+02,4873.477092,4.164651e+03,3.636986e+03,4720.779912,4616.818505
d_1924,42936.139744,14236.997691,10766.889962,17932.252091,2951.507622,6607.761126,5285.657799,3.087326e+03,4.469122e+03,4547.367476,1.750400e+03,2.494911e+03,4853.578716,6888.508140
d_1925,45335.734722,16910.836688,9631.872187,18793.025847,3428.453934,5027.940277,6124.538502,4.212093e+03,2.211852e-12,3402.255480,6.229617e+03,1.916861e+03,7774.172824,7219.802426
d_1926,56903.393692,19774.493581,15101.027408,22027.872703,8212.638482,2000.652135,6762.922560,5.051660e+03,7.404474e+02,7214.182012,7.146398e+03,4.872237e+03,9382.106901,5520.149185
d_1927,48297.399154,15639.861230,12028.204331,20629.333593,5623.259408,5873.457837,7828.857702,1.303759e+03,1.193801e+03,7772.198150,3.062205e+03,5.131290e+03,5250.551347,5258.019577
d_1928,51346.731507,19625.710712,12226.113401,19494.907394,5725.590514,5640.414775,7915.431796,2.134703e+02,3.705730e+03,5250.238081,3.270146e+03,4.645601e+03,9864.544152,5115.565968
d_1929,41599.020732,13401.834997,12257.575015,15939.610720,3425.291271,3824.013044,5204.235532,3.486071e+03,3.345579e+03,3048.765150,5.863231e+03,4.058059e+03,7326.877037,2016.899010
d_1930,44824.419646,14516.725496,14077.632677,16230.061473,4064.373168,658.383209,6012.617527,5.494688e+03,5.592621e+03,3581.410430,4.903601e+03,6.657160e+03,3569.635099,4289.930191
d_1931,44025.013390,12167.045963,14564.253047,17293.714380,1549.211659,2593.445146,9439.665240,3.711392e+03,6.017888e+03,3544.067808,5.002297e+03,3.157044e+03,6808.870478,2201.131576
d_1932,45545.389182,15523.566405,11761.173227,18260.649550,6413.798516,4117.129198,6012.809345,1.716912e+03,6.805104e+02,5423.037379,5.657625e+03,5.951478e+03,7668.659304,1903.429234
d_1933,56340.727142,20056.530525,12795.997122,23488.199496,5983.551984,5968.803066,9087.810058,2.448034e+03,4.116614e+03,3476.394841,5.202989e+03,8.561599e+03,5537.978896,5956.952653
d_1934,60969.929855,18882.258609,18055.805263,24031.865983,6499.073609,4295.763963,8075.616031,5.161412e+03,6.462213e+03,5921.697770,5.671894e+03,6.962147e+03,8608.903476,3311.207708
d_1935,40893.060414,13252.755324,9680.101752,17960.203339,4042.536873,6524.114968,6313.925362,1.079626e+03,3.551038e+03,3575.924195,2.553140e+03,1.716400e-23,6225.736385,7027.018939
d_1936,41999.895914,12675.820051,12685.371590,16638.704272,3907.384073,3338.086604,7412.202239,1.981031e+03,3.507618e+03,3742.381406,5.435372e+03,6.038492e+03,4278.251613,2359.076891
d_1937,38710.932481,10117.094918,11289.519812,17304.317751,4526.205972,2107.872098,6925.504194,3.744735e+03,4.737457e+03,1737.334983,4.814728e+03,2.510717e+03,3130.633509,4475.744308
d_1938,38175.507667,11193.683282,8476.511223,18505.313162,7101.711191,2141.664514,5688.143073,3.573794e+03,3.941139e+03,623.448289,3.911924e+03,4.146202e+03,3994.123809,3053.357760
d_1939,45081.682111,14913.983363,12760.619345,17407.079403,5782.619575,4737.847257,5937.637311,9.489753e+02,5.894593e+03,5591.972937,1.274053e+03,4.789149e+03,5009.355069,5115.479644
d_1940,52787.887107,17216.707239,13675.400915,21895.778953,4766.303806,9022.001763,6724.490166,1.382983e+03,2.904470e+03,4527.430654,6.243500e+03,4.753128e+03,4397.430020,8066.149582
d_1941,56199.581086,15441.782258,15036.680492,25721.118336,6481.822470,6786.323193,10528.102152,1.924871e+03,3.232003e+03,4816.629619,6.988048e+03,5.011957e+03,4761.029726,5668.795149